### ISSUE TITLE
Permission denied

### ISSUE THREAD

**Issue by CalebMadsen** [MDAnalysis/cellgrid#5]
Hello,
I am new to github, so please excuse me if this is a novice issue, but I am having trouble installing CellGrid. I get this error: 

"Permission denied (publickey).
fatal: Could not read from remote repository.

Please make sure you have the correct access rights
and the repository exists."

I typed the first line exactly as it was suggested. Am I missing something?

**Comment by backpropper** [comment]
After which step are you getting this error? You may need to add give root privileges for the last command (i.e. `sudo python setup.py install`)

**Comment by richardjgowers** [comment]
Hi Caleb,

I think my instructions are bad, try this line:
`git clone https://github.com/richardjgowers/cellgrid.git`

**Comment by CalebMadsen** [comment]
Hi,

That way works! I think I had to set up an SSH key first though. Anyway, now I get an error when I try to import cellgrid in python that says "unable to import cmath" Is cmath from something, or is it part of cellgrid?
